spring:
  application:
    name: demo

  datasource:
    url: jdbc:mysql://localhost:3360/transfers?allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=utf8&useUnicode=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Hibernate configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8081